project:
  type: website
  output-dir: docs

website:
  title: "Lucynda Young | Marketing Analytics Portfolio"
  site-url: "https://cynyng.github.io/portfolio/"
  navbar:
    logo: headshot.png
    pinned: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Digital Marketing"
        href: digital-marketing.qmd
      - text: "Marketing Analytics"
        href: marketing-analytics.qmd
      - text: "Interactive Presentation"
        href: presentation.qmd
      - text: "Website Analytics"
        href: website-analytics.qmd
      - text: "Resume"
        href: resume.qmd
    right:
      - icon: github
        href: https://github.com/Cynyng/portfolio
      - icon: linkedin
        href: https://www.linkedin.com/in/lucyndayoung/
  page-footer:
    left: "© 2026 Lucynda Young"
    right: "Built with Quarto | Marketing Analytics Portfolio"

format:
  html:
    theme:
      - darkly
      - styles.scss
    toc: false
    smooth-scroll: true
    page-layout: full
    css: styles.css
    link-external-newwindow: true

execute:
  freeze: auto
  warning: false
  message: false
